Fixed typo in nut.blt data
It was producing the error below if you try to `import boltspy`.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "%localappdata%\Local\Programs\Python\Python310\lib\site-packages\boltspy\__init__.py", line 26, in <module>
    repo = blt.Repository(rootpath)
  File "%localappdata%\Programs\Python\Python310\lib\site-packages\boltspy\bolttools\blt.py", line 289, in __init__
    cls = Class(cl)
  File "%localappdata%\Programs\Python\Python310\lib\site-packages\boltspy\bolttools\blt.py", line 134, in __init__
    self.parameters = Parameters(cl.get("parameters",{"types" : {}}))
  File "%localappdata%\Programs\Python\Python310\lib\site-packages\boltspy\bolttools\common.py", line 463, in __init__
    table._normalize_and_check_types(self.types)
  File "%localappdata%\Programs\Python\Python310\lib\site-packages\boltspy\bolttools\common.py", line 655, in _normalize_and_check_types
    raise ValueError("Column is missing for row: %s" % key)
ValueError: Column is missing for row: M16
```